name: Actions Test
on:
  push:
    branches:
      - dev
jobs:
  test:
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      TFC_ORG: ${{ secrets.TFC_ORG }}
      TFC_ENDPOINT: ${{ secrets.TFC_ENDPOINT }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create project
        id: tf-project
        uses: ./actions/tf-project
        with:
          name: "test-project"

      - name: Display project id
        run: echo ${{ steps.tf-project.outputs.project_id }}
